### PR TITLE
updated the barcode screenshot

### LINKED ISSUE #183: Update the barcode scanning screenshot
Barcode scanning is now in portrait and has a shorter, localized string. @adammichaelwood do you think it's worth updating screenshots for this kind of small change?

The screenshot itself is similar enough that it's not a very big deal but I notice that the alt text is very specific and could be misleading (landscape, thin red line).

### PR DESCRIPTION
**Pull request by troublemagnet**
Updated the screenshot to portrait mode and with a blue line(like it actually is)
closes #183

### CODE REVIEW

**Comment by troublemagnet** [comment]
@adammichaelwood  Can you help me with why the CI tests are timing out sir?

**Comment by adammichaelwood** [comment]
> Can you help me with why the CI build is timing out sir?
What happens when you run the build locally?

**Comment by adammichaelwood** [comment]
dirhtml, not htmldir

**Comment by troublemagnet** [comment]
@adammichaelwood  It builds successfully.

**Pull request closed without merging**
