### PR TITLE
Fix overflow lines in code-blocks

### LINKED ISSUE #305: Code samples require side scrolling
If a line in a code sample is too long, you have to scroll sideways.

I don't think this is ideal... but maybe it it (?).

At any rate, I think the fix is just some CSS to wrap overflow lines in code blocks.

If someone could do it, and submit a PR -- at least we could see if it is an improvement.
(It might not be.)

Note: I can imagine it being the case that some languages wrap better than others. For example, `rst` blocks will probably read much better when wrapped, but XML might not. Looking into how css classes are applied based on language, and making it something we could choose on a per-language basis would be extra cool.

### PR DESCRIPTION
**Pull request by ankita240796**
closes #305 

## What is included in this PR?
- Added wrap and unwrap class.
- Added default wrap for rst code-blocks.
- Added note on using wrap and unwrap classes.

### CODE REVIEW

**Comment by ankita240796** [comment]
selection_004
The fix works fine but space is left blank inside a block in some cases.
selection_003
Box-sizing can be changed in this case but I am not sure whether I should do this or not since box-sizing is same for all the blocks.

**Comment by adammichaelwood** [comment]
I like the idea of having wrapping on an as-needed basis. 
But I don't like so much clutter in the source files. There's little call for that.

Here's my thought:

 - a `wrap` class, as you have it

**Comment by ankita240796** [comment]
Thank you for the review @adammichaelwood. I will make the required changes.
I will take care about spacing. There was some indentation error due to which I had to this.

**Comment by ankita240796** [comment]
@adammichaelwood I have made the requested changes.

**Pull request merged**
