### PR TITLE
[WIP] Updated barcode screenshot

### LINKED ISSUE #183: Update the barcode scanning screenshot
Barcode scanning is now in portrait and has a shorter, localized string. @adammichaelwood do you think it's worth updating screenshots for this kind of small change?

The screenshot itself is similar enough that it's not a very big deal but I notice that the alt text is very specific and could be misleading (landscape, thin red line).

### PR DESCRIPTION
**Pull request by troublemagnet**
Updated the barcode scanner screenshot.
Earlier - Horizontally-oriented , red line
Now - Portrait mode , blue line
Closes #183

### CODE REVIEW

**Comment by troublemagnet** [comment]
@adammichaelwood apologies for multiple PRs sir. However the CI build still seems to time out.

**Comment by troublemagnet** [comment]
@adammichaelwood It builds successfully.

**Comment by adammichaelwood** [comment]
> However the CI build still seems to time out.

Right... so there's a problem. But when you close the PR, I can't easily go help you debug it.

**Comment by troublemagnet** [comment]
@adammichaelwood It didn't pass the tests so I thought it that my fork wasn't in sync with upstream. hence I pulled from master and then made a new pr.

**Comment by adammichaelwood** [comment]
> wasn't in sync with upstream. hence I pulled from master and then made a new pr.

You can actually pull `upstream master` into your working branch and the PR will update.

Also, unless there's serious merge conflicts, divergent branches can usually get merged back together in PRs.

It's not a big deal, but in the future -- closing PRs only to reopen new ones with the same content is a bit unhelpful.

**Comment by troublemagnet** [comment]
Sorry sir. I did it because I was absolutely clueless about it.

**Comment by adammichaelwood** [comment]
> Sorry sir. I did it because I was absolutely clueless about it

I know exactly how you feel...

**Comment by adammichaelwood** [comment]
The problem seems to be with git lfs.
Do you have git lfs installed and working properly?

**Comment by troublemagnet** [comment]
@adammichaelwood I didn't completely understand the problem. So I deleted my fork, studied about git lfs(didn't know about it) and fixed the issue. Can I make a new PR for the final time from my new fork?

**Comment by adammichaelwood** [comment]
That would be fine.

**Pull request closed without merging**
