### PR TITLE
Changes the code-block type for terminal commands

### PR DESCRIPTION
**Pull request by mish24**
This PR adds the following changes:
* It changed the default console type commands to use `none` as code-block type.
* Some of the restructured text examples used `rest`, changed all of them to `rst`, which is in accordance with the guide itself.
* Added a note for the use of `none`.

### CODE REVIEW

**Comment by mish24** [comment]
@adammichaelwood I'll change `none` to `console` here.

**Comment by mish24** [comment]
Now, 
* All examples of terminal commands are changed to code-block type `console`
* `rest` changed to `rst`.
@adammichaelwood Please have a look

**Comment by adammichaelwood** [comment]
Mentioning the code block lang declaration shouldn't be a formal `note`at the end of the doc.

You can just add a terminal command example to the code block that has the other examples.

Otherwise, it looks good.

**Comment by mish24** [comment]
@adammichaelwood I made the required updates. Added the `sh` code-block example too.

**Comment by adammichaelwood** [comment]
closes #168

**Pull request merged**
