### PR TITLE
line edit: fix consistency issue with bullet points

### PR DESCRIPTION
**Pull request by nhorton04**
#### What problems did you encounter?
Consistency issues with a list of bullet points on what was line 148. Fixed to be consistent, now is on line 147

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks so much for catching that and submitting a fix!

Since we're in the process of reworking our contribution guidelines, it would be really helpful to know what workflow you used and how it worked for you. Did you use the "Edit on Github" link? Use [the Docker setup](https://github.com/opendatakit/docs#building-and-viewing-documentation-locally)? Read through [the contributor guide](https://docs.opendatakit.org/contributing/)? Something else?! Thanks!

**Comment by nhorton04** [comment]
Hi Hélène,

I'm pretty new to this so please forgive me if my explanation doesn't fully make sense, and feel free to ask for clarification / correct me if I'm wrong.

I read through the contributor guide, which I found to be very helpful. I decided to start with a line edit, as suggested in the guide, so I looked for typos in reStructuredText documents in the docs/odk1-src/ directory on Github.

After I found a document containing a typo, I opened a version of this document stored locally on my computer in Atom text editor. I made the necessary changes in Atom, saved the file, then committed and pushed it to my own cloned repository (I think). Then I made the pull request, and voilà!

Please let me know if you have any questions or if something I said here is horrifically incorrect. 
I appreciate the mutually beneficial chance to contribute! 

Thanks,
Nick

**Comment by lognaturel** [comment]
Thanks so much, @nhorton04, that's super helpful! Everything you did sounds spot on for the complete workflow. 👍 

If you haven't already, consider joining the [ODK dev slack](http://slack.opendatakit.org/) in the #docs-code channel if you want to chat docs!

**Comment by nhorton04** [comment]
Thank you for the list! I'm still pretty confused and trying to figure this
all out. I'm doing some research on the ODK forums, and hopefully soon I'll
be knowledgable enough to solve some of those issues.

>

**Pull request merged**
