### PR TITLE
119 : Explain how Sphinx templating and theming works, for contributors guide

### PR DESCRIPTION
**Pull request by smartyrad**
Changes made:
1) Created a seperate document for sphinx consisiting of "Writing in Sphinx" and "Templates" sub sections.
2) Template overriding and Template extension(relation between base and child template) elucidated with examples.
3) A brief note on comparison between the previous theme and the 'better theme' has been listed in the "HIghlights" section.
4) For customisable themes, application of custom.css and custom.jss has been explained
5) Title formatting fixed
6) Links to official docs for Sphinx and Jinga have also been given

### CODE REVIEW

**Comment by adammichaelwood** [comment]
This is going to have some merge conflicts at the moment. Please make sure you pull the latest from `upstream master` and get everything sorted.

**Comment by adammichaelwood** [comment]
- Please do not move the Writing in Sphinx section out of The contributor's guide. That is not in scope for the issue #119.
 - Do not add a new Table of Contents directive. The new doc on working with templates should be added to the existing `Contributing` TOC directive.

The commit should only show two files changed from `master` --

 - new file, with the templating info
 - a one-line addition to `index.rst` adding the new file to the table of contents

(Pulling in from `upstream master` and starting a new branch from that, and then making these two changes will probably be the easiest approach, and also will solve your merge conflict also.)

**Comment by adammichaelwood** [comment]
Other issues:

 - Your section title format is not right. Please refer to contributors guide.
 - Your templating info contains a lot of information that is not actually needed, or is simply duplicated from the Sphinx or Jinja docs.

**Comment by smartyrad** [comment]
@adammichaelwood  Required changes made. Sorry for the mistake in the PR before

**Comment by adammichaelwood** [comment]
> Sorry for the mistake in the PR before

No worries. This is supposed to be a learning process. 
(For all of us, really.)

I hope my comments/corrections are not discouraging. 
We're just trying to get it right for the docs, and also pass on and promote best practices as much as possible.

**Comment by smartyrad** [comment]
@adammichaelwood The comments were not discouraging for sure. If there is a mistake then it has to be fixed :) . Is the PR looking good now ?

**Comment by smartyrad** [comment]
@adammichaelwood I have updated the file. Kindly check it out  :)

**Comment by adammichaelwood** [comment]
Please do not take the following as a discouragement from contributing on other issues.

I am going to close this PR without merging or requesting additional changes. I don't think that additional rounds of review and edits are going to fix fundamental problems with the content.

This is my fault, as I should not have let you -- or **anyone new to the project** -- work on this. 

Effective documentation must always come from a deep understanding of the subject matter. Deep understanding comes from using the tools, not from reading other documentation about them. Since you are mostly unfamiliar with Sphinx, and have not developed with it, having you try to write a guide on using it was not wise on my part. 

I appreciate your work and enthusiasm on this. There are lots of other issues you can work on.

**Pull request closed without merging**
