### PR TITLE
Displayed the glossary points in a proper manner

### PR DESCRIPTION
**Pull request by mish24**
Before the PR
screenshot from 2017-09-08 09-28-44

After the PR
screenshot from 2017-09-08 09-26-48

### CODE REVIEW

**Comment by adammichaelwood** [comment]
Thank you for your work.

Unfortunately, this change is not needed or helpful. The glossary uses a specific syntax, not headlines and bullets.

**Comment by adammichaelwood** [comment]
Also - please build the docs locally before submitting PRs.
If you had done so, you would have seen massive numbers or warnings, as this change broke all `:term:` links.

**Comment by mish24** [comment]
@adammichaelwood I got the warnings, but didn't know that is was not required. Sorry!

**Comment by adammichaelwood** [comment]
It's okay. We're all learning.

Maybe you could amend the contributors guide:
**If you submit a pull request that will create build errors, you must include a note mentioning what those errors are, and why they are ok to leave in.**

Should probably just say that we do not accept PRs with build errors or warnings. 
I originally thought we'd allow some warnings (particularly missing cross references, since that might indicate future-planning), but it's actually too complicated to sort out what to accept and not, so we just don't allow any warnings or errors at all.

**Comment by adammichaelwood** [comment]
You could also file an issue and then submit a PR adding info on the glossary syntax, and using the `:term:` cross reference.

http://www.sphinx-doc.org/en/stable/markup/para.html?highlight=glossary

http://www.sphinx-doc.org/en/stable/markup/inline.html#role-term

**Pull request closed without merging**
