### PR TITLE
Added upgrade guide for Aggregate

### LINKED ISSUE #228: Add documentation on upgrading Aggregate
We should have a new doc on how to upgrade Aggregate with details of various versions. @adammichaelwood  What do you think?

### PR DESCRIPTION
**Pull request by ankita240796**
closes #228 

## What is included in this PR?
- Added need for upgrading Aggregate
- Added upgrade steps and release notes for Aggregate
- Added upgrade admonition for Upgrade notes

### CODE REVIEW

**Comment by adammichaelwood** [comment]
This is good work.

I'm very curious about why you created a Upgrade Notes admonition, instead of using the existing Notes or Warning. I'm not opposed to the idea, but I don't really understand it.

**Comment by ankita240796** [comment]
@adammichaelwood I felt that since each version of Aggregate requires upgrade notes and they are different from general notes, tips. Further this admonition can also be used when we add upgrade docs in any other section. Also I think this improves readability. 
What do you think ?

**Comment by adammichaelwood** [comment]
So what is the difference between the upgrade notes, and the other notes also in the upgrade document?

**Comment by ankita240796** [comment]
Normal notes have general information but here we have the information specific to upgrade process.

**Comment by adammichaelwood** [comment]
I'm merging because the information is good.
I'm going to open an issue to discuss the Upgrade Note thing -- we might refactor it out.

**Pull request merged**
