### PR TITLE
removes curly quote transform

### LINKED ISSUE #513: Prevent smart quotes in spreadsheet samples
I noticed reviewing @jbeorse's PR that all quotes and ticks in spreadsheet samples seem to be rendered as smart quotes. That means samples can't be used from copying and pasting without replacing the quote types.

### PR DESCRIPTION
**Pull request by adammichaelwood**
closes #513 

## What is included in this PR?

 - `conf.py` is edited to make explicit the smartquotes option
     The transform is left ON for dashes and ellipses, but turned off for quotes
 - `requirements.txt` is updated, as the smartquotes options require later versions of Sphinx and docutils

## What problems did you encounter?

I would have preferred to only disable smartquotes within specific directives, 
as it is better to leave them on for normal prose.
But this would have required custom coding, I think,
as such an option does not currently exist.

(If this option is added in the future, we may want to consider it.)

### Updates to Sphinx and Docutils

The ability to specify options for the smartquotes parser was new in Sphinx 1.6.6,
prior to this PR, we are on 1.6.1

I *tried* updating to Sphinx 1.7, but this broke the custom directives.
If there is a reason in the future to upgrade past 1.6.x, we;ll need some debugging work.

In the end, I updated `requirements.txt` just to 1.6.6

### CODE REVIEW

**Comment by adammichaelwood** [comment]
I just realized I leaked some changes into this PR from another working branch.
Don't merge until this is fixed.

**Comment by adammichaelwood** [comment]
The stray changes are removed. 

This is ready for review/merge.

**Comment by adammichaelwood** [comment]
I'm tagging @lognaturel , since this was your issue.
And @yanokwa because I assume changes to requirements affect CircleCI.
(Cheers.)

**Comment by yanokwa** [comment]
I'm going to squash and merge this, but in the future, please rebase the commits so the commit history tells a better story. 

Rebasing and better commit messages are something I'm also working on and @lognaturel sent me these two great resources that helped me.
* https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
* https://dev.bleacherreport.com/small-commits-for-fun-and-profit-part-1-git-add-patch-c0966a562b10

**Pull request merged**
