### PR TITLE
[WIP] Documenting the usage of QR codes

### PR DESCRIPTION
**Pull request by mish24**
screenshot from 2017-09-10 12-05-46

This is just a basic skeleton of the page that'll have the information. There are several issues like:
1. Representing `Import/Export settings` using :guilabel: tag.
2. There are no screenshots, and the ones I got from https://opendatakit.org/2017/06/configure-collect-on-many-devices-with-qr-codes/ have a very different resolution.
3. The names and titles need to be shortened.

More understanding of generating QR codes through a program (I don't know how that is done). @adammichaelwood A little help for that?

### CODE REVIEW

**Comment by adammichaelwood** [comment]
this is the right direction. You'll need to provide a complete JSON example.
(You could get a real, live example by generating a QR code in app and then decoding and decompressing it. Be sure to notice, though, that default settings are omited - so you might not get a complete list of settings from a live install)

**Comment by adammichaelwood** [comment]
Do you mean in the app or from a separate program?

**Comment by mish24** [comment]
@adammichaelwood I just got it! I will update this PR soon. I'm really sorry for taking so long

**Comment by mish24** [comment]
@adammichaelwood I am still on this, just that android studio and emulator take a lot of space and it's really really slow. Can I add the rest of the changes as of now? I'll add JSON example once I get it

**Comment by adammichaelwood** [comment]
> emulator take a lot of space and it's really really slow. 

Yes. The docs even say so. :)

The PR isn't that helpful without the JSON format, so we can just hold it.
But it isn't urgent. If you come back around to this in a few days, that will be just fine.

**Comment by adammichaelwood** [comment]
I mean -- you can whatever commits. But I'm not going to merge the PR until is complete.

**Comment by mish24** [comment]
@adammichaelwood I am closing this PR due to conflicts. I'll open a new PR

**Pull request closed without merging**
