### PR TITLE
WIP: Video directive for Sphinx

### PR DESCRIPTION
**Pull request by jumperskirt**
video directive written in video.py
added node and directive to conf.py
issue #66
error when i attempted to build:

> Exception occurred:
  File "conf.py", line 206, in setup
    from . import video
KeyError: "'__name__' not in globals"

was not sure how to configure conf.py and ss.py

### CODE REVIEW

**Comment by adammichaelwood** [comment]
I can't really do anything with this. Debugging an error is one thing, but it isn't clear what you think this is supposed to even accomplish.

**Comment by jumperskirt** [comment]
thank you for your feedback

**Comment by lognaturel** [comment]
@jumperskirt Could you please say a little bit more about what you think this should do? It looks like it comes from [here](https://github.com/ryfeus/lambda-packs/blob/master/Selenium_PhantomJS/source/docutils/parsers/rst/directives/images.py) (it should be credited!) and is meant for figures and simple images -- did you see a reference that suggested it could be used with videos?

**Comment by jumperskirt** [comment]
hello! first, i surely didn't mean to not credit; where does one credit? in
the commit message? as a comment in the file itself? second, yes, the
video.py i added is just the image directive with 'image' swapped out for
'video', and then i added video as a custom extension in the config.py,
along with the desired output formats

i did this because after going through the spinx tutorial, and the
reStructured docs and adam's input that processing the video was likely
outside the scope of the extension, i thought the video directive would
look and act like the image directive (and therefore copy over the videos
and put them in their own vid directory upon build, like it does currently
for img);

i knew i hadn't gotten it right, but i was trying to run the program to see
if the error messages could help me figure out what i needed to be
rethinking. i was having trouble understanding the aforementioned error
message and submitted the pr hoping for guidance in that area. is there a
better way to ask for code review besides gists or pull requests?

at any rate, it seems i'm not on the right track, so i'll go back over the
tutorial and welcome any other suggestions you might have

**Comment by adammichaelwood** [comment]
Thanks for this.

A PR is the right venue for a code review.
I just need a little more info on what your thinking is and what you are trying to accomplish.

Building off an existing image directive makes some sense, as there are definitely similarities.

Here's what I recommend:

 - start with the unmodified code, and see if you can get things to work
     - this probably involves diving into how to load extensions in Sphinx
 - then modify and see how that updates the output

Changing one thing at a time makes it more clear where the problem is.

**Comment by jumperskirt** [comment]
will do, thank you

**Comment by nadaa** [comment]
@jumperskirt, please check [this](https://groups.google.com/forum/#!topic/sphinx-users/_z00m3zoRAY).

**Comment by jumperskirt** [comment]
@nadaa hello! thanks for sharing; i too ran into that thread during my internet peregrinations; it seems to be explaining the way everyone (odk included) is currently doing the video embedding (without the video directive i am attempting to write)—did i miss something?

@adammichaelwood i did manage to get rid of the errors i was getting before by just starting over and trying one thing a a time as you suggested; i now have a video directive written  and get a message that the build succeeded, but with a [different] error and with no video output. i will submit a [WIP] PR, and if you have any suggestions while i continue to try different things, i'd greatly appreciate it

**Comment by adammichaelwood** [comment]
you can commit on the same branch and keep everything in this PR

**Comment by adammichaelwood** [comment]
> and with no video output.

restructured text has an internal representation of each node in a document. each builder has a specific way of rendering those nodes.

Since images are a standard part of the document model, every builder has a representation for it. But if you add a new node type ("video"), the html builder has no understanding of that node, so it doesn't have any way of rendering it.

So a new rst directive that introduces a new document node type has to include details on how the builder(s) should render it.

If you look at the sphinx contrib plugins, i'm sure at least a few of them cover a similar use case and would provide some insight into how to provide rendering help to the builder through the plugin.

**Comment by jumperskirt** [comment]
yes, thank you for the feedback! i have been taking a look at the youtube
plugin but will check out others too

**Comment by adammichaelwood** [comment]
Closing due to inactivity.

**Pull request closed without merging**
