### PR TITLE
Added Android security tips

### LINKED ISSUE #61: Android-level security recommendations
For example, if enumerators are able to install apps, they can install camera apps that may let them bypass certain requirements (see [here](https://forum.opendatakit.org/t/disable-choosing-an-image-video-or-audio/9338)).

Another example -- turning on Android-level data encryption means when the device is locked, no one can see the data. It's an easier alternative to using encrypted forms that offers most of the benefits.

### PR DESCRIPTION
**Pull request by ankita240796**
closes #61 

## What is included in this PR?
Added security recommendations for Android.

### CODE REVIEW

**Comment by adammichaelwood** [comment]
This is going to need to be updated to reflect the changes made in #361 
Basically -- the content related to this needs to be in its own page, and then that page added to the TOC listing on the collect-best-practices page.

**Comment by ankita240796** [comment]
Sure, I will do that as soon as #361 is merged

**Comment by ankita240796** [comment]
@adammichaelwood I indented the images.

**Comment by ankita240796** [comment]
@adammichaelwood I made the required changes.

**Pull request merged**
