### PR TITLE
WIP: Contrib guide update

### PR DESCRIPTION
**Pull request by adammichaelwood**
addresses #161 
addresses #823 
addresses #805 
addresses #716 
addresses #581 
addresses #485 

#### What is included in this PR?

A massive rewrite of the contributor guide.

Here's what I am trying to accomplish:

 - put everything into numbered list procedure style (combined with the details hiding, this makes the doc easier to navigate, I think)
 - split Linux/Mac/Windows commands into toggled tabs
 - provide the simplest procedure that is the most likely to work in the largest number of cases 
 - add notes and other details wherever there is likely to be confusion or problem
 - remove notes and explanations that are overly complicated or esoteric
 - remove advanced procedures that first time contributors are unlikely to need

#### What is left to be done in the addressed issue?

SO VERY MUCH.

This is a WORK IN PROGRESS.

##### Syntax has problems

It has a bunch of sphinx-build errors and warnings
and some messed up formatting (like every item in a list being numbered `1.`)

##### Windows make commands not done.

I stopped trying to wrap my head around Windows Powershell make files and just forged ahead.
So in this current draft, the build commands for powershell include all the needed subcommands for compiling the sources into `tmp` directories.

##### Content moved and not put anywhere

There's a `.scratch` file that is just stuff I yanked out of the guide and haven't put back anywhere.

##### Style guide testing is broken

Like @danbjoseph, I could not get style testing to work on individual files.
(I have documented this in #844)

For the mean time, I have simply left out local style testing from the guide.

##### I haven't even touched Edit on GitHub

That might be a future PR.

##### Basic editing and proofreading

Not even a little.

#### What problems did you encounter?

See #844.

The tabs feature, especially with code samples, creates a lot of nesting.
This pushed my Emacs multi-mode rst parsing to the breaking point
and weirdly caused tab insertion in all sorts of places.
I switched to Visual Studio Code, which I kinda like.

Because this took me so long to write, 
my trial of Windows via Parallels on Mac expired.
I am going to purchase a license but (incredibly!)
I also lost my wallet and am waiting on replacement credit cards.
So currently, some of the Windows procedures and PowerShell commands are reconstructed from notes and the internet,
but have not been double checked by me.
If you have access to Windows
(especially a clean install that you have not previously put Python and git on)
checking all those procedures would be a great help.
(I will also do this myself when my credit card replacements arrive.)

#### Anything else?

I changed a few syntax style things as an experiment.
I like the changes a lot,
but I can change them back if others disagree.

#### Three spaces instead of two.

Because the `.. directive::` syntax has three columns (two dots and a space) before the directive,
and also a numbered list items has three columns (hash sign, dot, space) before the item text,
using three spaces to indent beneath these makes everything line up.
I've been playing with this in other projects and found it to be helpful.

Given the DEEP nesting of this document,
I thought it would help me keep it clear in the source,
which it did.

#### `.. code::` instead of `.. code-block::`

They mean exactly the same thing in `.rst`
(one is actually an alias for the other)
and `.. code::` is less to type.

### Note to reviewers

Even at this point, I would appreciate some review.
However, given all the things I mentioned above, you will waste a lot of time/energy if you try to start correcting spelling, syntax, and similar.

Please focus on:

 - overall organization (is it a good way to present the information?)
 - clarity of style (does it make sense, especially for beginners)
 - factual correctness (is the information correct? do the commands do what it says they do? will the procedures work in all cases?)

### CODE REVIEW

**Comment by adammichaelwood** [comment]
@danbjoseph I'd appreciate any input on this you have as a new contributor.

**Comment by adammichaelwood** [comment]
> .. code:: instead of .. code-block::

Here's an interesting side note...

Apparently these two things are NOT equivalent:

```
.. code:: none


.. code-block:: none
```

The first one produces a warning: ` WARNING: Cannot analyze code. No Pygments lexer found for "none".`
The second one does not.

**Comment by adammichaelwood** [comment]
All the major broken structural stuff has been fixed.

There's still work here. But it is in a state that you could pull it and run the build and get a good sense of things.

So... if someone wants to do that... I'd be happy for any content review as I continue working through some of the technical problems.

**Comment by danbjoseph** [comment]
for anyone who knows some git but not not a lot, this is what i did to take a look at the changes (as this was new to me and not something I had done before):
```
git remote add adammichaelwood https://github.com/adammichaelwood/odk-docs.git
git fetch adammichaelwood
git branch -v -a 
git checkout adammichaelwood/contrib-guide-update
```

**Comment by danbjoseph** [comment]
I will try and actually read through in the entirety and follow the instructions. But my initial reaction after a quick scan..

> - put everything into numbered list procedure style (combined with the details hiding, this makes the doc easier to navigate, I think)

It's still a little overwhelming at first glance. But I don't think the volume of content can be made not a little overwhelming. I think the list and hidden details is a nice improvement that helps.

> - split Linux/Mac/Windows commands into toggled tabs

nice touch!

> - provide the simplest procedure that is the most likely to work in the largest number of cases
> - add notes and other details wherever there is likely to be confusion or problem
> - remove notes and explanations that are overly complicated or esoteric
> - remove advanced procedures that first time contributors are unlikely to need

I think by-and-large the changes touch on all these.

**Comment by danbjoseph** [comment]
unrelated. after clicking a link in the left sidebar nav, both the nav and the main page refresh to the top. for the lengthy nav, this means that the open section showing your current location is frequently lower down off the page. is there anyway to get the left nav to scroll down to bring the active section to the top on page load? would this even be desirable?

**Comment by lognaturel** [comment]
I think that overall this brings in some good improvements that would be really great to get in so we can iterate with smaller PRs. @adammichaelwood do you think you could get this to a mergeable state? I think that would entail fixing the build and resolving merge conflicts. I didn't see any critically pressing content edits.

The currently-published contribution guide is out of sync with reality and this has confused contributors like @zestyping so I think it's important to get those changes soon. There's also now a [Docker option](https://github.com/opendatakit/docs/blob/67f9e8a5a59041c5d6648b6785bd44dc86b2e381/README.md#using-docker) that does lower the bar significantly for Windows users in particular.

**Comment by DEskinazi** [comment]
I'm very interested in helping how I can. It's possible I may need a little guidance moving forward, but I'm eager to assist.

**Pull request merged**
