### PR TITLE
Line edit 96

### PR DESCRIPTION
**Pull request by apaluya**
closes #

addresses #96 

My first PR w/ ODK ;-)

## What is included in this PR?

Changed line 1525, adding a hyphen for "docs-related issue".

## What problems did you encounter?

Not a problem, exactly. I'm using Atom, and on my first attempted save it automatically removed trailing whitespace in 48 places in the 'contributing.rst' doc. Maybe that's not a bad thing in general, but to err on the safe side, I turned this function off, refreshed from master, and then made my change once again.

I'm here because of Adam's talk at Berkeley WeWork last week. Well done!

### CODE REVIEW

**Comment by lognaturel** [comment]
Welcome, @apaluya!! 💫

**Comment by adammichaelwood** [comment]
>  I'm using Atom, and on my first attempted save it automatically removed trailing whitespace in 48 places in the 'contributing.rst' doc.

It would be fine, or not, to remove this white space. 

(This explains some things, too -- I've seen several PRs that remove a lot of trailing whitespace and now I bet this is the cause.)

Thanks so much for jumping in. Come introduce yourself in the [ODK Slack](https://opendatakit.slack.com) -- the docs-code channel is where we talk about docs.

**Comment by apaluya** [comment]
Hi Adam,
I guess I’d need an invite to the ODK Slack workspace?
I created a Slack acct for this email address.
Thanks again,
Paul

**Comment by lognaturel** [comment]
Heya @apaluya! You can self-invite at http://slack.opendatakit.org/ 😊

**Comment by lognaturel** [comment]
Hah, note my totally appropriate hyphen usage.

**Comment by apaluya** [comment]
Great! Thanks, Helene
(sorry, ascii-only ;-)
And I do appreciate the warm welcome.

**Pull request merged**
