### PR TITLE
Document front appearance for barcode widget

### LINKED ISSUE #853: Add front appearance for barcode
As of Collect v1.17.0, the `front` appearance can be used with a barcode question to force the front camera to be used. More info and sample form at https://github.com/opendatakit/collect/pull/2453

This should be added to https://docs.opendatakit.org/form-question-types/#barcode-widget

### PR DESCRIPTION
**Pull request by grzesiek2010**
closes #853

#### What is included in this PR?
It documents front appearance for barcode widget.

### CODE REVIEW

**Comment by lognaturel** [comment]
The images are quite large. Other question type images are about 28kbs but these are over a mb. In general, images need to be resized and compressed before upload.

In this case, how about not including images at all since they're the same as the rear-facing camera screenshots?

**Comment by lognaturel** [comment]
@grzesiek2010 want to make sure you saw my comment so we can get this merged! 😊

**Comment by grzesiek2010** [comment]
Sorry for the delay! I'll fix it soon.

**Comment by grzesiek2010** [comment]
> In this case, how about not including images at all since they're the same as the rear-facing camera screenshots?

yeah maybe you are right it's not really needed. Fixed.

**Pull request merged**
