### PR TITLE
Update pushing and pulling files (#861)

### LINKED ISSUE #861: Convert "App Designer->Pushing and Pulling" Docs Updates
In [this forum thread](https://forum.opendatakit.org/t/community-contributions-to-upcoming-odk-2-0-documentation-refresh/11324/8), ODK 2 users have contributed updates to the App Designer documentation. To resolve this issue, the changes outlined in [Pushing and Pulling Files 9.1.18 CGK.docx](https://github.com/opendatakit/docs/files/2413546/Pushing.and.Pulling.Files.9.1.18.CGK.docx) should be implemented on the [corresponding page](https://docs.opendatakit.org/odk2/build-app/#pushing-and-pulling-files).

This issue involves no new copy writing, just implementing existing copy changes in the proper Sphinx syntax.

### PR DESCRIPTION
**Pull request by vmaldosan**
closes #861

#### What is included in this PR?
Minor updates from [Pushing.and.Pulling.Files.9.1.18.CGK.docx](https://github.com/opendatakit/docs/files/2413546/Pushing.and.Pulling.Files.9.1.18.CGK.docx)

#### What problems did you encounter?
The last section in the aforementioned document is confusing (hence the draft PR). Pending clarification on which changes are needed for the _Troubleshooting_ section (if any).

### CODE REVIEW

**Comment by wbrunette** [comment]
@vmaldosan the pull request is still in draft mode. If it's ready for review please move the status from "draft" to "open" by clicking on "ready for review".

**Comment by vmaldosan** [comment]
Hi @wbrunette, I first would like to clarify what should I do with the _Troubleshooting_ section at the end of Pushing.and.Pulling.Files.9.1.18.CGK.docx. Is it meant to be inserted as it is right after the tip? Maybe it's because I'm using LibreOffice to track the changes on that document, so it looks like this: 
image

If you can confirm that this is the expected content and format of that section, I'll add it to this PR and mark it ready for review.
Thanks!

**Comment by wbrunette** [comment]
**Removing the formatting and hyperlinks the text should be the following (the link shown in your screenshot should be included and the commands "adb devices" should be differentiated to show you type them in) :** 

There are several issues that may occur while trying to push your survey onto your device. Below are some common issues and tip and tricks to help:
•	Try checking adb –version. If the version does not show, make sure that Android SDK is appropriately installed on your computer because this is what installs the Android Debug Bridge (adb) software. 
•	Check that your computer sees your device. In your command window type the command adb devices. It should show a device detected.
•	Check device to see if it has a message about authorizing the computer. If so, authorize the device. 
•	Check device settings to ensure USB debugging is enabled and device is liked as a media device (not camera or other settings)
•	Make sure your app-designer only has the necessary working files. Any random files or older versions of your survey saved within app-designer will cause the push to fail.
•	Do not have any Excel forms open on your computer. If you do, this will cause errors with $filename or ~$filename in the filepath when pushing.

**Comment by vmaldosan** [comment]
I took the liberty to replace _liked_ for _linked_, as well as adding a couple of `:program:` tags.

**Comment by vmaldosan** [comment]
Thanks, @wbrunette 🎉 🎉 🎉

**Pull request merged**
