### PR TITLE
Adds doc on using Google Drive with Collect

### LINKED ISSUE #164: A doc on using google drive in ODK collect
I found there is an option to set "google drive" as a server in ODK collect app. I think it will be good to include this in the ODK Docs?

### PR DESCRIPTION
**Pull request by nadaa**
This is a short Doc of connecting Google Drive to ODK Collect. 

Closes #164

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for doing this, @nadaa! I don't see any license on <https://www.google.com/earth/outreach/tutorials/odkcollect_drive.html Unless we find a license, we probably can't build off of it. @nadaa, did you find a license anywhere on the Earth Outreach website?

**Comment by nadaa** [comment]
Welcome, @lognaturel. I look at the site, but no license appears!.

**Comment by adammichaelwood** [comment]
This is content we could really use, but I think building off the Google documentation is a problem. You could try to contact someone through the Google Earth forum, but I imagine that isn't going to go anywhere.

I suggest going through this process yourself (if you haven't already) and then try writing the doc entirely yourself. I can help you think about structure, etc. if you want to talk about it as you work.

**Comment by nadaa** [comment]
Hi @adammichaelwood, I checked the steps on my side before writing.
I will contact google earth and see.

**Comment by nadaa** [comment]
@adammichaelwood , I couldn't contact google earth outreach team. I posted a question on their group. I will update you once I get a response. 

I will be working to improve this document and have real examples with clear steps. 

Thank you

**Comment by lognaturel** [comment]
@yanokwa may also be seeing someone from that team this week so hopefully he may be able to get them to license the content so it can be reused. But @nadaa including real examples with clear steps sounds fantastic.

**Comment by yanokwa** [comment]
I've got an email out to our friends at Google to see if they can license that content.

**Pull request closed without merging**
