### PR TITLE
Widget guide

### PR DESCRIPTION
**Pull request by adammichaelwood**
re: issue #50 
This is a **basic** widget guide, and there is more work to do:

- add appearance and other widget options (before closing this issue)
- add Enketo screen shots (cf issue #58)
- add downloadable sample xls sheets (cf issue #47)
- deal with design issues so screenshots are more easily viewable (cf #59)
- fix my typos etc.

### CODE REVIEW

**Comment by adammichaelwood** [comment]
I meant to submit this PR against a new feature branch instead of Master, but I can't figure out how to fix that...
(sorry) 
I can delete and resubmit if needed

**Comment by lognaturel** [comment]
Looks like it's right to me! I think it would be ok to merge a first pass to master and keep iterating on it. Or is it that you want chunks to be more polished before they go out? If so, you should be able to create the branch from the GitHub interface and then change the target in this pull request.

**Comment by adammichaelwood** [comment]
I thought we'd publish this and keep adding to it.

**Comment by lognaturel** [comment]
This is great, then. You have a feature branch on your repo and once it gets reviewed it can be merged to master and published. 👍

**Comment by yanokwa** [comment]
This looks like a good start but I want to wait until, per the issue, all the widgets at https://opendatakit.org/help/form-design/examples are documented. I think this should be doable by the end of the week.

**Comment by yanokwa** [comment]
@adammichaelwood Loving the ongoing improvements to the docs! Looking forward to seeing the rest of the appearances so I can merge them in tomorrow.

**Comment by adammichaelwood** [comment]
was hoping to have this finished today, but I have the selection widgets left.

**Comment by adammichaelwood** [comment]
widget guide completed; please review and merge @yanokwa

**Pull request merged**
